---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  type: NodePort
  ports:
  - port: 8125
    targetPort: 8125
    protocol: UDP
    name: http
  selector:
    app: telegraf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        
