apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: NodePort
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    nodePort: 30021
    name: ftps
  - port: 31000
    targetPort: 31000
    nodePort: 31000
    name: ftps-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'ps aux | egrep [t]elegraf'
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - mountPath: /ftp/user
          name: ftps-volume
      volumes:
      - name: ftps-volume
        hostPath:
          path: /data
          type: DirectoryOrCreate
