apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: local-config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
          #- 127.0.0.240/28
          - 192.168.99.102/28
---
apiVersion: v1
kind: Service
metadata:
  name: local-nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: local-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-nginx-deployment
  labels:
    app: local-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: local-nginx
  template:
    metadata:
      labels:
        app: local-nginx
    spec:
      containers:
      - name: local-nginx
        image: local-nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
