apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 31000
    targetPort: 31000
    name: ftps-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /ftp/user
          name: ftps-volume
      volumes:
      - name: ftps-volume
        hostPath:
          path: /data
          type: DirectoryOrCreate
